services:
  - type: web
    name: telegram-keyword-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_TELEGRAM_ID
        sync: false
      - key: KEYWORD
        sync: false
